rule trim:
    input:
        forward="{prefix}%s%s/{sample, .*?}_R1.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['rejoin_samples']),
        reverse="{prefix}%s%s/{sample, .*?}_R2.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['rejoin_samples'])
    output:
        pairedforward="{prefix}%s%s/Paired/{sample, .*?}_R1.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
        unpairedforward="{prefix}%s%s/Unpaired/{sample, .*?}_R1.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
        pairedreverse="{prefix}%s%s/Paired/{sample, .*?}_R2.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim']),
        unpairedreverse="{prefix}%s%s/Unpaired/{sample, .*?}_R2.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['trim'])
    log:
        "{prefix}%s{sample}_trimmomatic.log" % config['dirs']['logs']
    benchmark:
        "{prefix}%s{sample}_trimmomatic.benchmark" % config['dirs']['logs']
    conda:
      "envs/spike_trim.yaml"
    threads:
        4
    shell:
        "java"
        " -Xmx4g"
        " -XX:ParallelGCThreads={threads}"
        " -jar ${{CONDA_PREFIX}}/share/trimmomatic-0.33-1/trimmomatic.jar"
        " PE -threads {threads} -phred33"
        " {input.forward}"
        " {input.reverse}"
        " {output.pairedforward}"
        " {output.unpairedforward}"
        " {output.pairedreverse}"
        " {output.unpairedreverse}"
        " ILLUMINACLIP:${{CONDA_PREFIX}}/share/trimmomatic-0.33-1/adapters/TruSeq3-PE.fa:2:30:10 CROP:99 LEADING:10 TRAILING:10 SLIDINGWINDOW:4:15 MINLEN:36"
        " > {log} 2>&1"
