# DNA material of a sample might be split and loaded into several lanes to
# increase coverage. We here use information from SampleSheet and merge fastq.gz
# files from demultiplexing if necessary, otherwise we just use soft links

rule rejoin_sample:
    input:
        lambda wildcards: ["%s%s%s/%s/%s_L%03i_%s_001.fastq.gz" % (wildcards.prefix, config['dirs']['intermediate'], config['stepnames']['demultiplex'], wildcards.run, wildcards.sample, int(lane), wildcards.direction)
                           for lane in get_lanes_for_sampleID(wildcards.sample, SAMPLESHEETS)]
    benchmark:
        "{prefix}%s{run}/{sample}_{direction}.benchmark" % config['dirs']['benchmarks']
    log:
        "{prefix}%s{run}/{sample}_{direction}.log" % config['dirs']['logs']
    output:
        "{prefix}%s%s/{run,[^\/]+XX}/{sample, .*?}_{direction,R[1|2]}.fastq.gz" % (config['dirs']['intermediate'], config['stepnames']['rejoin_samples'])
    threads:
        1
    shell:
        'if [[ $(echo "{input}" | wc -w) -gt 1 ]]; then '
        # you can just concatenate multiple *.gz files into one, while
        # content when decompressed remains the same!
        'cat {input} > {output} 2> {log};'
        'else '
        'cp -l -v {input} {output} 2> {log}; '
        'chmod u+w {output} 2>> {log}; '
        'fi; '
